@baseUrl = http://localhost:3333
@AuthToken = {{authenticate.response.body.access_token}}

POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Jhonatan",
  "email": "jhonatan1@gmail.com",
  "password": "123456"
}

###
# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "jhonatan1@gmail.com",
  "password": "123456"
}

###
# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
  "title": "Nova perguntas 2",
  "content": "Teste"
}

####
# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

####
# @name edit_question
PUT {{baseUrl}}/questions/6ed3de55-746f-43e9-9406-101716e466c5
Content-Type: application/json
Authorization: Bearer {{AuthToken}}

{
  "title": "New title",
  "content": "New content",
  "attachments": "1"
}